title: Fahim Khan Tushar
description: BS in Microbiology.
baseurl: "/cv/"
url: ""
resume_url: "Resume.pdf"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
