title: Fahim Khan Tushar
description: Software Engineer, QA @ Therap (BD) Ltd.
baseurl: "/remple/"
url: ""
resume_url: "resume.pdf"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
